---
name: General checks

# yamllint disable-line rule:truthy
on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  spelling-check:
    name: Spell check using typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
      - name: Spell Check Repo
        uses: crate-ci/typos@44e2070e6017f834bf069503acb35ca0ca0b75f2  # v1.47.1

  trailing-whitespaces-check:
    name: Trailing whitespaces check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
      - run: ./bin/trailing_spaces.py --Werror $(git ls-files)

  newlines-check:
    name: Newlines check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
      - run: ./bin/newline_at_eof.py --Werror $(git ls-files)

  trufflehog-scan:
    name: Secrets check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          fetch-depth: 0
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
